Update high.php
I have added a condition if there is a session (session_token) is called.
Because in this case the cookies were removed and a query was sent showing an error:

Notice: Undefined index: session_token in /x/index.php on line 13

Fatal error: Uncaught Error: Call to undefined function dvwaSessionGrab() in /x/function.php:13 Stack trace: #0 /x/function.php(22): dvwaMessagePush('CSRF token is i...') #1 /x/index.php(13): checkToken('9477d94f904941d...', NULL, 'index.php') #2 {main} thrown in /x/function.php on line 13